{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interview-app.fullname" . }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEMO_API_KEY: {{ .Values.secret.demoApiKey | quote }}
{{- end }}
